"""
번역 프롬프트 템플릿 모듈

v1: 소비자 페이지 크롤링 기반 번역 프롬프트
gb_*: 작가웹 GB 등록 전용 프롬프트
"""
# v1 프롬프트
from .japanese import JAPANESE_PROMPT, JAPANESE_TITLE_PROMPT, JAPANESE_OPTION_PROMPT
from .english import ENGLISH_PROMPT, ENGLISH_TITLE_PROMPT, ENGLISH_OPTION_PROMPT

# GB 등록 전용 프롬프트
from .gb_english import (
    GB_TITLE_PROMPT_EN, GB_DESCRIPTION_PROMPT_EN,
    GB_KEYWORD_PROMPT_EN, GB_OPTION_PROMPT_EN,
    GB_DESCRIPTION_REBUILD_PROMPT_EN,
)
from .gb_japanese import (
    GB_TITLE_PROMPT_JA, GB_DESCRIPTION_PROMPT_JA,
    GB_KEYWORD_PROMPT_JA, GB_OPTION_PROMPT_JA,
    GB_DESCRIPTION_REBUILD_PROMPT_JA,
)

__all__ = [
    # v1
    'JAPANESE_PROMPT', 'JAPANESE_TITLE_PROMPT', 'JAPANESE_OPTION_PROMPT',
    'ENGLISH_PROMPT', 'ENGLISH_TITLE_PROMPT', 'ENGLISH_OPTION_PROMPT',
    # GB
    'GB_TITLE_PROMPT_EN', 'GB_DESCRIPTION_PROMPT_EN', 'GB_KEYWORD_PROMPT_EN', 'GB_OPTION_PROMPT_EN',
    'GB_DESCRIPTION_REBUILD_PROMPT_EN',
    'GB_TITLE_PROMPT_JA', 'GB_DESCRIPTION_PROMPT_JA', 'GB_KEYWORD_PROMPT_JA', 'GB_OPTION_PROMPT_JA',
    'GB_DESCRIPTION_REBUILD_PROMPT_JA',
]
