"""
번역 프롬프트 템플릿 모듈
"""
from .japanese import JAPANESE_PROMPT, JAPANESE_TITLE_PROMPT, JAPANESE_OPTION_PROMPT
from .english import ENGLISH_PROMPT, ENGLISH_TITLE_PROMPT, ENGLISH_OPTION_PROMPT

__all__ = [
    'JAPANESE_PROMPT',
    'JAPANESE_TITLE_PROMPT', 
    'JAPANESE_OPTION_PROMPT',
    'ENGLISH_PROMPT',
    'ENGLISH_TITLE_PROMPT',
    'ENGLISH_OPTION_PROMPT',
]
